package com.xkt.siot.domain;
// Generated 2016-4-19 15:14:08 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Delivery generated by hbm2java
 */
@Entity
@Table(name = "delivery", catalog = "siotdb", uniqueConstraints = @UniqueConstraint(columnNames = "uid"))
@DynamicInsert(true)
@DynamicUpdate(true)
public class Delivery implements java.io.Serializable {

    private Integer id;
    private int uid;
    private String realname;
    private String phone;
    private String area;
    private String address;
    private String postcode;
    private Date rectime;

    public Delivery() {
    }

    public Delivery(int uid, String realname, String phone, String area, String address) {
        this.uid = uid;
        this.realname = realname;
        this.phone = phone;
        this.area = area;
        this.address = address;
    }

    public Delivery(int uid, String realname, String phone, String area, String address, String postcode, Date rectime) {
        this.uid = uid;
        this.realname = realname;
        this.phone = phone;
        this.area = area;
        this.address = address;
        this.postcode = postcode;
        this.rectime = rectime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "uid", unique = true, nullable = false)
    public int getUid() {
        return this.uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    @Column(name = "realname", nullable = false, length = 45)
    public String getRealname() {
        return this.realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    @Column(name = "phone", nullable = false, length = 45)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "area", nullable = false, length = 100)
    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    @Column(name = "address", nullable = false, length = 100)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "postcode", length = 45)
    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rectime", length = 19)
    public Date getRectime() {
        return this.rectime;
    }

    public void setRectime(Date rectime) {
        this.rectime = rectime;
    }
}
