package com.xkt.siot.domain;
// Generated 2016-4-19 15:14:08 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", catalog = "siotdb")
@DynamicInsert(true)
@DynamicUpdate(true)
public class Log implements java.io.Serializable {

    private Integer id;
    private int cid;
    private Integer did;
    private int fcode;
    private Integer motion;
    private Float mox;
    private Float moy;
    private Float moz;
    private Float moacc;
    private Float humidity;
    private Float temperature;
    private Float battery;
    private Date rectime;

    public Log() {
    }

    public Log(int cid, int fcode) {
        this.cid = cid;
        this.fcode = fcode;
    }

    public Log(int cid, Integer did, int fcode, Integer motion, Float mox, Float moy, Float moz, Float moacc, Float humidity, Float temperature, Float battery, Date rectime) {
        this.cid = cid;
        this.did = did;
        this.fcode = fcode;
        this.motion = motion;
        this.mox = mox;
        this.moy = moy;
        this.moz = moz;
        this.moacc = moacc;
        this.humidity = humidity;
        this.temperature = temperature;
        this.battery = battery;
        this.rectime = rectime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "cid", nullable = false)
    public int getCid() {
        return this.cid;
    }

    public void setCid(int cid) {
        this.cid = cid;
    }

    @Column(name = "did")
    public Integer getDid() {
        return this.did;
    }

    public void setDid(Integer did) {
        this.did = did;
    }

    @Column(name = "fcode", nullable = false)
    public int getFcode() {
        return this.fcode;
    }

    public void setFcode(int fcode) {
        this.fcode = fcode;
    }

    @Column(name = "motion")
    public Integer getMotion() {
        return this.motion;
    }

    public void setMotion(Integer motion) {
        this.motion = motion;
    }

    @Column(name = "mox", precision = 12, scale = 0)
    public Float getMox() {
        return this.mox;
    }

    public void setMox(Float mox) {
        this.mox = mox;
    }

    @Column(name = "moy", precision = 12, scale = 0)
    public Float getMoy() {
        return this.moy;
    }

    public void setMoy(Float moy) {
        this.moy = moy;
    }

    @Column(name = "moz", precision = 12, scale = 0)
    public Float getMoz() {
        return this.moz;
    }

    public void setMoz(Float moz) {
        this.moz = moz;
    }

    @Column(name = "moacc", precision = 12, scale = 0)
    public Float getMoacc() {
        return this.moacc;
    }

    public void setMoacc(Float moacc) {
        this.moacc = moacc;
    }

    @Column(name = "humidity", precision = 12, scale = 0)
    public Float getHumidity() {
        return this.humidity;
    }

    public void setHumidity(Float humidity) {
        this.humidity = humidity;
    }

    @Column(name = "temperature", precision = 12, scale = 0)
    public Float getTemperature() {
        return this.temperature;
    }

    public void setTemperature(Float temperature) {
        this.temperature = temperature;
    }

    @Column(name = "battery", precision = 12, scale = 0)
    public Float getBattery() {
        return this.battery;
    }

    public void setBattery(Float battery) {
        this.battery = battery;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rectime", length = 19)
    public Date getRectime() {
        return this.rectime;
    }

    public void setRectime(Date rectime) {
        this.rectime = rectime;
    }
}
