package com.xkt.siot.domain;
// Generated 2016-4-19 15:14:08 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", catalog = "siotdb")
@DynamicInsert(true)
@DynamicUpdate(true)
public class Profile implements java.io.Serializable {

    private Integer id;
    private int uid;
    private String description;
    private Boolean motion;
    private Float ma;
    private Float ms;
    private Boolean humi;
    private Float hh;
    private Float hl;
    private Boolean temp;
    private Float th;
    private Float tl;
    private Date updatetime;

    public Profile() {
    }

    public Profile(int uid) {
        this.uid = uid;
    }

    public Profile(int uid, String description, Boolean motion, Float ma, Float ms, Boolean humi, Float hh, Float hl, Boolean temp, Float th, Float tl, Date updatetime) {
        this.uid = uid;
        this.description = description;
        this.motion = motion;
        this.ma = ma;
        this.ms = ms;
        this.humi = humi;
        this.hh = hh;
        this.hl = hl;
        this.temp = temp;
        this.th = th;
        this.tl = tl;
        this.updatetime = updatetime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "uid", nullable = false)
    public int getUid() {
        return this.uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    @Column(name = "description", length = 45)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "motion")
    public Boolean getMotion() {
        return this.motion;
    }

    public void setMotion(Boolean motion) {
        this.motion = motion;
    }

    @Column(name = "ma", precision = 12, scale = 0)
    public Float getMa() {
        return this.ma;
    }

    public void setMa(Float ma) {
        this.ma = ma;
    }

    @Column(name = "ms", precision = 12, scale = 0)
    public Float getMs() {
        return this.ms;
    }

    public void setMs(Float ms) {
        this.ms = ms;
    }

    @Column(name = "humi")
    public Boolean getHumi() {
        return this.humi;
    }

    public void setHumi(Boolean humi) {
        this.humi = humi;
    }

    @Column(name = "hh", precision = 12, scale = 0)
    public Float getHh() {
        return this.hh;
    }

    public void setHh(Float hh) {
        this.hh = hh;
    }

    @Column(name = "hl", precision = 12, scale = 0)
    public Float getHl() {
        return this.hl;
    }

    public void setHl(Float hl) {
        this.hl = hl;
    }

    @Column(name = "temp")
    public Boolean getTemp() {
        return this.temp;
    }

    public void setTemp(Boolean temp) {
        this.temp = temp;
    }

    @Column(name = "th", precision = 12, scale = 0)
    public Float getTh() {
        return this.th;
    }

    public void setTh(Float th) {
        this.th = th;
    }

    @Column(name = "tl", precision = 12, scale = 0)
    public Float getTl() {
        return this.tl;
    }

    public void setTl(Float tl) {
        this.tl = tl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updatetime", length = 19)
    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}
