package com.xkt.siot.domain;
// Generated 2016-4-19 15:14:08 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ucorm generated by hbm2java
 */
@Entity
@Table(name = "ucorm", catalog = "siotdb")
public class Ucorm implements java.io.Serializable {

    private Integer id;
    private int uid;
    private int cid;

    public Ucorm() {
    }

    public Ucorm(int uid, int cid) {
        this.uid = uid;
        this.cid = cid;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "uid", nullable = false)
    public int getUid() {
        return this.uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    @Column(name = "cid", nullable = false)
    public int getCid() {
        return this.cid;
    }

    public void setCid(int cid) {
        this.cid = cid;
    }
}
