package com.xkt.siot.domain;
// Generated 2016-4-19 15:14:08 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "siotdb", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
@DynamicInsert(true)
@DynamicUpdate(true)
public class User implements java.io.Serializable {

    private Integer id;
    private String username;
    private String password;
    private Boolean sex;
    private String nickname;
    private String signature;
    private Date birthday;
    private String email;
    private String phone;
    private String qq;
    private String weibo;
    private String portrait;
    private Integer score;
    private Integer auth;
    private Date rectime;

    public User() {
    }

    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public User(String username, String password, Boolean sex, String nickname, String signature, Date birthday, String email, String phone, String qq, String weibo, String portrait, Integer score, Integer auth, Date rectime) {
        this.username = username;
        this.password = password;
        this.sex = sex;
        this.nickname = nickname;
        this.signature = signature;
        this.birthday = birthday;
        this.email = email;
        this.phone = phone;
        this.qq = qq;
        this.weibo = weibo;
        this.portrait = portrait;
        this.score = score;
        this.auth = auth;
        this.rectime = rectime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "username", unique = true, nullable = false, length = 45)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "password", nullable = false, length = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "sex")
    public Boolean getSex() {
        return this.sex;
    }

    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    @Column(name = "nickname", length = 45)
    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    @Column(name = "signature", length = 100)
    public String getSignature() {
        return this.signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "birthday", length = 10)
    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    @Column(name = "email", length = 45)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "phone", length = 45)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "qq", length = 45)
    public String getQq() {
        return this.qq;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }

    @Column(name = "weibo", length = 100)
    public String getWeibo() {
        return this.weibo;
    }

    public void setWeibo(String weibo) {
        this.weibo = weibo;
    }

    @Column(name = "portrait", length = 100)
    public String getPortrait() {
        return this.portrait;
    }

    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    @Column(name = "score")
    public Integer getScore() {
        return this.score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    @Column(name = "auth")
    public Integer getAuth() {
        return this.auth;
    }

    public void setAuth(Integer auth) {
        this.auth = auth;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rectime", length = 19)
    public Date getRectime() {
        return this.rectime;
    }

    public void setRectime(Date rectime) {
        this.rectime = rectime;
    }
}
